/*
 * Blog API
 *
 * This is a mini blog.
 *
 * API version: 1.0.0
 * Contact: chris-ju@qq.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Review struct {
	Id int32 `json:"id,omitempty"`
	Publish string `json:"publish,omitempty"`
}
